#!/bin/sh

mkdir -p ipkg/home/retrofw/games/quake2
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/games
cp quake2.elf ipkg/home/retrofw/games/quake2/quake2
cp quake2.png ipkg/home/retrofw/games/quake2/quake2.png
cp -r baseq2 ipkg/home/retrofw/games/quake2

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: quake2
Version: 20190216
Description: FPS game
Section: games
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/quake2
Depends:
Source: https://github.com/gameblabla/quake2' > control

print '2.0' > debian-binary

print 'title=quake2
description=FPS game
exec=/home/retrofw/games/quake2/quake2
clock=600
' > home/retrofw/apps/gmenu2x/sections/games/quake2

tar -czvf control.tar.gz control
tar -czvf data.tar.gz home
ar rv ../quake2.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
